[package]
name = "sillydrageon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
lorax = { path = "lorax" }
func = { path = "dialects/func" }
arith = { path = "dialects/arith" }
x86 = { path = "dialects/x86" }
