on: push
name: Clippy check

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Run Clippy
        run: cargo clippy --fix --all-targets --all-features

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix clippy lints
